config/routes.rb
Rails.application.routes.draw do
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to = 'homes#top'
  get 'about' => 'homes#about'
  get 'search' => 'searches#search'

  resources :post_images, only: [:index, :new, :create, :show, :destroy] do
    collection do
      get :follower_post
    end
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
      member do
        get :followers
        get :followeds
      end
  end

  resources :genres, only: [:index, :show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post_image
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :post_images, dependent: :destroy

  validates :name, presence: {message: "を選んでください"}

end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post_image

end

app/models/post_image.rb
class PostImage < ApplicationRecord
  belongs_to :user
  belongs_to :genre
  attachment :image
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :image, presence: {message: "を選んでください"}
  validates :title, presence: true
  validates :introduction, presence: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :post_images, dependent: :destroy
  has_many :post_commnets, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :image

  has_many :relationships, foreign_key: :follower_id, dependent: :destroy
  has_many :followers, through: :relationships, source: :followed
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: :followed_id, dependent: :destroy
  has_many :followeds, through: :reverse_of_relationships, source: :follower

  validates :name, presence: {message: "は必須項目です"}

  def is_followed_by?(user)
    reverse_of_relationships.find_by(follower_id: user.id).present?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(@user)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @post_image = PostImage.find(params[:post_image_id])
    favorite = current_user.favorites.new(post_image_id: @post_image.id)
    favorite.save

  end

  def destroy
    @post_image = PostImage.find(params[:post_image_id])
    favorite = current_user.favorites.find_by(post_image_id: @post_image.id)
    favorite.destroy

  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @post_images = PostImage.page(params[:page]).reverse_order
    @genres = Genre.all
  
  end
  
  
  def about
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  def create
    @post_image = PostImage.find(params[:post_image_id])
    comment = PostComment.new(post_comment_params)
    comment.user_id = current_user.id
    comment.post_image_id = @post_image.id
    comment.save
    render :post_comments
    
  end
  
  def destroy
    if current_user.id == comment.user.id
      PostComment.find_by(id: params[:id]).destroy
    end
    @post_image = PostImage.find(params[:post_image_id])
    render :post_comments
    
  end
  
  private
  
  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end
  
  
end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController
  def new
    @post_image = PostImage.new
    @genres = Genre.all
  end

  def create
    @post_image = PostImage.new(post_image_params)
    @post_image.user_id = current_user.id
    if @post_image.save
      redirect_to post_images_path
    else
      @genres = Genre.all
      render :new
    end

  end

  def index
    @post_images = PostImage.page(params[:page]).reverse_order
    @genres = Genre.all


  end

  def show
    @post_image = PostImage.find(params[:id])
    @post_comment = PostComment.new

  end

  def destroy
    @post_image = PostImage.find(params[:id])
    if current_user.id == comment.user.id
      @post_image.destroy
    end
    redirect_to post_images_path

  end

  def follower_post
    @post_images = PostImage.page(params[:page]).reverse_order.where(user_id: [current_user.follower_ids])
    @genres = Genre.all
  end


  private

  def post_image_params
    params.require(:post_image).permit(:title, :image, :introduction, :genre_id)
  end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    follower = current_user.relationships.build(followed_id: params[:user_id])
    follower.save
    redirect_to request.referrer

  end

  def destroy
    follower = current_user.relationships.find_by(followed_id: params[:user_id])
    follower.destroy
    redirect_to request.referrer

  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @model = params[:model]
    @word = params[:word]
    @post_image = search_for(@model, @word)
    @post_images = @post_image.page(params[:page]).reverse_order
    @genres = Genre.all


  end

  private

  def search_params
    params.require(:search).permit(:model, :word)
  end

  def search_for(model, word)
    if model == "PostImage"
      PostImage.where("title LIKE ?", "%#{word}%")
    elsif model == "Genre"
      PostImage.where(genre_id: word)
    else
      redirect_to request.referer
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @post_images = @user.post_images.page(params[:page]).reverse_order
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  def followeds
    user = User.find(params[:id])
    @users = user.followeds
  end

  private

  def user_params
    params.require(:user).permit(:name, :image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/_favorite.html.erb
<% if obj.favorited_by?(current_user) %>
  <%= link_to post_image_favorites_path(obj), method: :delete, remote: true do %>
    <i class="fas fa-heart fa-lg" style="color:red;"> <%= obj.favorites.count %></i>
  <% end %>
<% else %>
  <%= link_to post_image_favorites_path(obj), method: :post, remote: true do %>
    <i class="fas fa-heart fa-lg" style="color:silver;"> <%= obj.favorites.count %></i>
  <% end %>
<% end %>

app/views/favorites/create.js.erb
$("#favorite_buttons_<%= @post_image.id %>").html("<%= j(render "favorites/favorite", obj: @post_image) %>");

app/views/favorites/destroy.js.erb
$("#favorite_buttons_<%= @post_image.id %>").html("<%= j(render "favorites/favorite", obj: @post_image) %>");

app/views/post_comments/_comment.html.erb
<div class="row">
  <% post_image.post_comments.each do |post_comment| %>
    <div class="col-lg-4 my-2 mx-2">
      <p><%= attachment_image_tag post_comment.user, :image, size: "50x50", fallback: "no_image.jpg" %></p>
      <p><%= post_comment.created_at.strftime("%Y/%m/%d") %></p>
      <p>
        <% if post_comment.user == current_user %>
          <%= link_to "削除", post_image_post_comment_path(post_comment.post_image, post_comment), method: :delete, remote: true,class: "btn btn-outline-danger" %>
        <% end %>
      </p>
    </div>
    <div class="col-lg-7 my-2 mx-2">
      【コメント】<p><%= post_comment.comment %></p>
    </div>
  <% end %>
</div>

app/views/post_comments/_form.html.erb
<div class="card mx-auto col-md-8 col-xl-10 pt-3 my-3 mx-4">
  <%= form_with(model: [post_image, post_comment], remote: true) do |f| %>
    <p><%= f.text_area :comment, rows:"8", placeholder: "コメントを記入",class: "form-control" %></p>
    <p class="my-3 text-right">
      <%= f.submit "送信",class: "btn btn-outline-dark" %>
    </p>
  <% end %>
</div>

app/views/post_comments/post_comments.js.erb
$("#comment_area").html("<%= j(render 'post_comments/comment', post_image: @post_image) %>");
$("textarea").val("");

app/views/post_images/_index.html.erb
<div class="container-fuild">
  <div class="row justify-content-center mx-0">
    <div class="col-sm-6 px-0 py-2 text-center align-self-center border border-white bg-dark">
      <%= link_to "新着投稿", post_images_path, class: "text-white h2" %>
    </div>
    <div class="col-sm-6 px-0 py-2 text-center align-self-center border border-white bg-dark">
      <%= link_to "タイムライン", follower_post_post_images_path, class: "text-white h2" %>
    </div>
  </div>
  <div class="row justify-content-center px-0 mx-0">
    <% post_images.each do |post_image| %>
    <div class="card col-md-5 col-xl-3 pt-3 my-3 mx-4">
      <div class="post-index-image">
        <%= link_to post_image_path(post_image.id) do %>
          <%= attachment_image_tag post_image, :image, size: "300x420", class: "card-img-top"; %>
        <% end %>
      </div>
      <div class="card-body">
        <div class="profile-icon">
          <%= link_to user_path(post_image.user.id) do %>
            <%= attachment_image_tag post_image.user, :image, size: "60x60", fallback: "no_image.jpg" %>
          <% end %>
        </div>
        <div class="row">
          <span class="col-6 px-0 text-left"><%= post_image.user.name %></span>
          <span class="col-6 px-0 text-right">
          <% if post_image.user != current_user %>
            <%= render "users/follow_system", obj: post_image.user %>
          <% end %>
          </span>
        </div>
      </div>
    </div>
    <% end %>
  </div>
  <div class="row justify-content-center px-0 mx-0">
    <%= paginate post_images %>
  </div>
</div>

app/views/post_images/follower_post.html.erb
<div class="container-fuild">
  <div class="row mx-0 py-2">
    <div class="col-lg-2">
      <%= render "searches/genre_search", genres: @genres %>
    </div>
    <div class="col-lg-10">
      <%= render "post_images/index", genres: @genres, post_images: @post_images %>
    </div>
  </div>
</div>

app/views/post_images/index.html.erb
<div class="container-fuild">
  <div class="row mx-0 py-2">
    <div class="col-lg-2">
      <%= render "searches/genre_search", genres: @genres %>
    </div>
    <div class="col-lg-10">
      <%= render "post_images/index", genres: @genres, post_images: @post_images %>
    </div>
  </div>
</div>

app/views/post_images/new.html.erb
<div class="container">
  <div class="row justify-content-center mt-5 border border-dark bg-light h5">
　　<div class="col-md-8 my-5">
      <%= form_with model: @post_image, local: true do |f| %>
      <%= render "layouts/errors", obj: @post_image %>
        <p><%= f.attachment_field :image %></p>
        <p><%= f.text_field :title, placeholder: "タイトル名",class: "form-control" %></p>
        <p><%= f.collection_select :genre_id, @genres, :id, :name, {prompt: "ジャンル"}, class: "form-control col-3" %></p>
        <p><%= f.text_area :introduction, placeholder: "投稿の説明",class: "form-control", rows: 15 %></p>
        <div class="text-center">
          <%= f.submit "アップロード",class: "btn btn-outline-dark" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/post_images/show.html.erb
<div class="container my-5 py-5 bg-light">
  <div class="card mx-auto col-md-8 col-xl-10 pt-3 my-3 mx-4">
    <div class="post-show-image">
      <%= attachment_image_tag @post_image, :image, class: "card-img-top"; %>
    </div>
    <div class="card-body h5">
      <div class="row">
        <div class="col-md-4 col-lg-3 col-xl-2">
          <i class="fas fa-comment-dots fa-lg"> <%= @post_image.post_comments.count %></i>
        </div>
        <div class="col-md-4 col-lg-3 col-xl-2">
          <div id="favorite_buttons_<%= @post_image.id %>">
            <%= render "favorites/favorite", obj: @post_image %>
          </div>
        </div>
      </div>
      <div class="row justify-content-between">
        <div class="mt-3">
          <div class="profile-icon">
            <%= link_to user_path(@post_image.user) do %>
              <%= attachment_image_tag @post_image.user, :image, size: "60x60", fallback: "no_image.jpg" %>
            <% end %>
          </div>
          <span><%= @post_image.user.name %></span>
        </div>
        <div class="mt-3 text-right">
          <% if @post_image.user != current_user %>
            <%= render "users/follow_system", obj: @post_image.user %>
          <% end %>
        </div>
      </div>
      <div class="mt-3">
        【タイトル】<p class="mt-2 ml-2"><%= @post_image.title %></p>
        【ジャンル】<p class="mt-2 ml-2"><%= @post_image.genre.name %></p>
        <p>【投稿説明】</p>
          <p class="py-4 px-2 border border-2 raunded" style="line-height:2.5rem">
            <%= @post_image.introduction %>
          </p>
        <p> 投稿日時:<%= @post_image.created_at.strftime("%Y/%m/%d") %></p>
        <% if @post_image.user == current_user %>
          <%= link_to "削除", post_image_path(@post_image), method: :delete, class: "btn btn-outline-danger" %>
        <% end %>
      </div>
      <div class="border border-2">
        <div id="comment_area">
          <%= render "post_comments/comment", post_image: @post_image %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container py-2 my-2 bg-light">
  <div class="comment_form">
    <%= render "post_comments/form", post_image: @post_image, post_comment: @post_comment %>
  </div>
</div>

app/views/users/_follow_system.html.erb
<% if user_signed_in? %>
  <% if obj.is_followed_by?(current_user) %>
    <%= link_to user_relationships_path(obj), method: :delete do %>
      <button class="btn btn-secondary">フォロー中</button>
    <% end %>
<% else %>
    <%= link_to user_relationships_path(obj), method: :post do %>
      <button class="btn btn-light">フォローする</button>
    <% end %>
  <% end %>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="row justify-content-center mt-5 border border-dark bg-light">
　　<div class="col-md-8 my-5">
      <%= form_with model:@user, local: true do |f| %>
        <div class="text-center">
          <div class="profile-icon">
            <%= attachment_image_tag @user, :image, size: "300x300", fallback: "no_image.jpg" %>
          </div>
        </div>
        <p class="my-4 text-center"> <%= f.attachment_field :image %></p>
        <%= render "layouts/errors", obj: @user %>
        <p>【ユーザー名】<%= f.text_field :name, placeholder: "ユーザー名",class: "form-control" %></p>
        <p>【自己紹介】　<%= f.text_area :introduction, placeholder: "投稿の説明",class: "form-control", rows: 15 %></p>
        <div class="text-center">
          <%= f.submit "変更を保存",class: "btn btn-outline-dark" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/followeds.html.erb
<div class="container-fuild">
  <h2 class="my-4 py-3 text-center text-white bg-dark">フォローされているユーザー</h2>
</div>
<div class="container bg-light">
  <% @users.each do |user| %>
    <div class="row justify-content-center border-bottom">
      <div class="col-3 mx-0 my-4 text-center">
        <div class="profile-icon">
          <%= link_to user_path(user) do %>
            <%= attachment_image_tag user, :image, size: "60x60", fallback: "no_image.jpg" %>
          <% end %>
        </div>
      </div>
      <div class="col-3 mx-0 my-4 text-center align-self-center">
        <%= link_to user_path(user) do %>
          <%= user.name %>
        <% end %>
      </div>
      <div class="col-3 mx-0 my-4 text-center align-self-center">
        <%= link_to followers_user_path(user) do %>
          <%= user.followers.count %>フォロー
        <% end %>
        <%= link_to followers_user_path(user) do %>
          <%= user.followeds.count %>フォロワー
        <% end %>
      </div>
      <div class="col-2 mx-0 my-4 text-center align-self-center">
        <% if user != current_user %>
          <% if user.is_followed_by?(current_user) %>
            <%= link_to user_relationships_path(user), method: :delete do %>
              <button class="btn btn-secondary">フォロー中</button>
            <% end %>
          <% else %>
            <%= link_to user_relationships_path(user), method: :post do %>
              <button class="btn btn-light">フォローする</button>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/followers.html.erb
<div class="container-fuild">
  <h2 class="my-4 py-3 text-center text-white bg-dark">フォロー中のユーザー</h2>
</div>
<div class="container bg-light">
  <% @users.each do |user| %>
    <div class="row justify-content-center border-bottom">
      <div class="col-3 mx-0 my-4 text-center">
        <div class="profile-icon">
          <%= link_to user_path(user) do %>
            <%= attachment_image_tag user, :image, size: "60x60", fallback: "no_image.jpg" %>
          <% end %>
        </div>
      </div>
      <div class="col-3 mx-0 my-4 text-center align-self-center">
        <%= link_to user_path(user) do %>
          <%= user.name %>
        <% end %>
      </div>
      <div class="col-3 mx-0 my-4 text-center align-self-center">
        <%= link_to followers_user_path(user) do %>
          <%= user.followers.count %>フォロー
        <% end %>
        <%= link_to followers_user_path(user) do %>
          <%= user.followeds.count %>フォロワー
        <% end %>
      </div>
      <div class="col-2 mx-0 my-4 text-center align-self-center">
        <% if user != current_user %>
          <% if user.is_followed_by?(current_user) %>
            <%= link_to user_relationships_path(user), method: :delete do %>
              <button class="btn btn-secondary">フォロー中</button>
            <% end %>
          <% else %>
            <%= link_to user_relationships_path(user), method: :post do %>
              <button class="btn btn-light">フォローする</button>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container-fuild my-5 py-2 bg-light border border-secondary">
  <div class="row h4">
    <div class="col-md-6 col-xl-4 pt-3 my-3 mx-4">
      <div class="row justify-content-center">
        <div class="profile-icon">
         <%= attachment_image_tag @user, :image, size: "120x120", fallback: "no_image.jpg" %>
        </div>
      </div>
      <div class="row mt-3 justify-content-center text-center">
        <div class="col-4">
          <%= link_to followers_user_path(@user) do %>
            <%= @user.followers.count %>フォロー
          <% end %>
        </div>
        <div class="col-4">
          <%= link_to followeds_user_path(@user) do %>
            <%= @user.followeds.count %>フォロワー
          <% end %>
        </div>
      </div>
      <div class="mt-3 text-center">
        <% if @user.id == current_user.id %>
          <%= link_to "プロフィール", edit_user_path(@user),class: "btn btn-outline-dark btn-lg btn-block fas fa-user-cog" %>
        <% else %>
          <%= render "users/follow_system", obj: @user %>
        <% end %>
      </div>
    </div>
    <div class="col-md-5 col-xl-7 pt-3 my-3">
      <div class="mt-2 ml-3 text-left h4">
        <%= @user.name %>
      </div>
      <div class="mt-4 text-left">
        【自己紹介】
        <p><%= @user.introduction %></p>
      </div>
    </div>
  </div>
</div>
<div class="container-fuild my-5 py-2 ">
  <h2 class="text-center border border-white text-white py-3 bg-dark"><%= @user.name %>の投稿</h2>
  <div class="row justify-content-center">
    <% @post_images.each do |post_image| %>
    <div class="card col-md-5 col-xl-3 pt-3 my-3 mx-4">
      <div class="post-index-image">
        <%= link_to post_image_path(post_image.id) do %>
          <%= attachment_image_tag post_image, :image, size: "300x420", class: "card-img-top"; %>
        <% end %>
      </div>
      <div class="card-body">
        <div class="row">
          <div class="col-md-4 col-lg-3">
            <%= link_to post_image_path(post_image.id) do %>
              <i class="fas fa-comment-dots fa-lg"> <%= post_image.post_comments.count %></i>
            <% end %>
          </div>
          <div class="col-md-4 col-lg-3">
            <div id="favorite_buttons_<%= post_image.id %>">
              <%= render "favorites/favorite", obj: post_image %>
            </div>
          </div>
        </div>
        <div class="mt-3 h5">
          【タイトル】<p class="mt-2 ml-2"><%= post_image.title %></p>
          【ジャンル】<p class="mt-2 ml-2"><%= post_image.genre.name %></p>
        </div>
      </div>
    </div>
    <% end %>
  </div>
  <div class="row justify-content-center">
    <%= paginate @post_images %>
  </div>
</div>