config/routes.rb
Rails.application.routes.draw do
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to = 'homes#top'
  get 'about' => 'homes#about'
  get 'search' => 'searches#search'

  resources :post_images, only: [:index, :new, :create, :show, :destroy] do
    collection do
      get :follower_post
    end
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
      member do
        get :followers
        get :followeds
      end
  end

  resources :genres, only: [:index, :show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post_image
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :post_images, dependent: :destroy

  validates :name, presence: {message: "を選んでください"}

end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post_image

end

app/models/post_image.rb
class PostImage < ApplicationRecord
  belongs_to :user
  belongs_to :genre
  attachment :image
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :image, presence: {message: "を選んでください"}
  validates :title, presence: true
  validates :introduction, presence: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :post_images, dependent: :destroy
  has_many :post_commnets, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :image

  has_many :relationships, foreign_key: :follower_id, dependent: :destroy
  has_many :followers, through: :relationships, source: :followed
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: :followed_id, dependent: :destroy
  has_many :followeds, through: :reverse_of_relationships, source: :follower

  validates :name, presence: {message: "は必須項目です"}

  def is_followed_by?(user)
    reverse_of_relationships.find_by(follower_id: user.id).present?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(@user)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @post_image = PostImage.find(params[:post_image_id])
    favorite = current_user.favorites.new(post_image_id: @post_image.id)
    favorite.save

  end

  def destroy
    @post_image = PostImage.find(params[:post_image_id])
    favorite = current_user.favorites.find_by(post_image_id: @post_image.id)
    favorite.destroy

  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @post_images = PostImage.page(params[:page]).reverse_order
    @genres = Genre.all
  
  end
  
  
  def about
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @model = params[:model]
    @word = params[:word]
    @post_image = search_for(@model, @word)
    @post_images = @post_image.page(params[:page]).reverse_order
    @genres = Genre.all


  end

  private

  def search_params
    params.require(:search).permit(:model, :word)
  end

  def search_for(model, word)
    if model == "PostImage"
      PostImage.where("title LIKE ?", "%#{word}%")
    elsif model == "Genre"
      PostImage.where(genre_id: word)
    else
      redirect_to request.referer
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @post_images = @user.post_images.page(params[:page]).reverse_order
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  def followeds
    user = User.find(params[:id])
    @users = user.followeds
  end

  private

  def user_params
    params.require(:user).permit(:name, :image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<div class="input_error">
  <ul class="list-unstyled mb-5">
    <% if obj.errors.any? %>
      <% obj.errors.full_messages.each do |message| %>
        <li class="my-2"><%= message %></li>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/layouts/_footer.html.erb
<footer class="container-fuild px-0 mt-5 bg-dark">
  <h4 class="mt-5 py-5 text-center text-white">
    CopyRight © Styles.inc
  </h4>
</footer>

app/views/layouts/_header.html.erb
    <header class="container-fluid px-0">
      <nav class="navbar navbar-lg navbar-dark bg-dark pr-3">
        <a class="navbar-brand mx-auto", data-turbolinks="false", href="/"><%= image_tag('logo.jpg', size: '200x150') %></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerlist" aria-controls="navbarTogglerlist" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarTogglerlist">
          <ul class="navbar-nav ml-auto mt-2 mt-lg-0 mb-1">
          <% if user_signed_in? %>
            <li class="h4 ml-auto">
              <%= link_to "投稿一覧", post_images_path, class: "text-white" %>
            </li>
            <li class="h4 ml-auto">
              <%= link_to "新規投稿", new_post_image_path, class: "text-white" %>
            </li>
            <li class="h4 ml-auto">
              <%= link_to "マイページ", user_path(current_user.id), class: "text-white" %>
            </li>
            <li class="h4 ml-auto">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete,  class: "text-white" %>
            </li>
          <% else %>
            <li class="h4 ml-auto">
              <%= link_to "HOME", root_path, data: {"turbolinks" => false}, class: "text-white" %>
            </li>
            <li class="h4 ml-auto">
              <%= link_to "ABOUT", about_path, data: {"turbolinks" => false}, class: "text-white" %>
            </li>
            <li class="h4 ml-auto">
              <%= link_to "ログイン", new_user_session_path, class: "text-white" %>
            </li>
            <li class="h4 ml-auto">
              <%= link_to "新規登録", new_user_registration_path, class: "text-white" %>
            </li>
        <% end %>
          </ul>
          <%= render "searches/form" %>
        </div>
      </nav>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Styles</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/cb9870c1ab.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
      <main>
        <%= yield %>
      </main>
    <%= render "layouts/footer" %>
  </body>
</html>